---
- name: load conf
  include_vars: "conf.yml"
- name: create package
  ansible.builtin.command:
    cmd: tar -czvf ../assets.tgz {{ asterisk_sound_directory }} {{ asterisk_moh_directory }}
    creates: assets.tgz
