---
- hosts: baseinstall
  become: true
  vars:  
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
    src: "../src"
  tasks:
    - include: provision.yml  
